version: '3.8'

services:
  jenkins_docker:
    container_name: jenkins_docker
    image: docker:dind
    hostname: 
    ports: jenkins_docker
      - "2376:2376"
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - "jenkins-docker-certs:/certs/client"
      - "jenkins_home:/var/jenkins_home"
    networks:
      - common
  configserver:
    container_name: configserver
    image: ggnanasekaran77/configserver
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:8888/ || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    hostname: configserver
    networks:
      - common
  jenkins:
    image: ggnanasekaran77/jenkins
    container_name: jenkins
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "./jenkins/shared-lib:/tmp/shared-lib"
      - "jenkins-docker-certs:/certs/client:ro"
    environment:
      CASC_JENKINS_CONFIG: "/usr/share/jenkins/ref/jenkins.yml"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      DOCKER_HOST: "tcp://jenkins_docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - configserver
      - jenkins_docker
    links:
      - configserver
      - jenkins_docker
    networks:
      - common

networks:
  common:
    driver: bridge
volumes:
  jenkins_home:
  jenkins-docker-certs:
  jenkins-data:
