version: '3.8'

services:
  configserver:
    container_name: configserver
    image: ggnanasekaran77/configserver
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:8888/ || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    hostname: configserver
    networks:
      - common

  jenkins:
    image: ggnanasekaran77/jenkins
    container_name: jenkins
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "./jenkins/shared-lib:/tmp/shared-lib"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      CASC_JENKINS_CONFIG: "/usr/share/jenkins/ref/jenkins.yml"
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - configserver
    links:
      - configserver
    networks:
      - common

networks:
  common:
    driver: bridge
volumes:
  jenkins_home:
